//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeamProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tracker
    {
        public string day_played { get; set; }
        public string week_played { get; set; }
        public string who_won { get; set; }
        public Nullable<int> points { get; set; }
    }
}
